name: Build ComputerBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Executable
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller --onefile main.py --name "ComputerBuild"
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            pyinstaller --onefile main.py --name "ComputerBuild"
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            pyinstaller --onefile main.py --name "ComputerBuild" --osx-bundle-identifier com.example.computerbuild --windowed --clean
            # Отключаем подпись (иначе будет ошибка)
            codesign --remove-signature dist/ComputerBuild || true
          fi

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: ComputerBuild-${{ matrix.os }}
          path: dist/*
